version: "3.3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - backend

  app-order:
    build:
      args:
        user: sammy
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: app-order
    container_name: app-order
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - backend

#  mysql-order:
#   image: mysql:5.7
#   container_name: mysql-order
#   restart: unless-stopped
#   env_file:
#     - .env
#   environment:
#     SERVICE_TAGS: dev
#     SERVICE_NAME: mysql
#   volumes:
#     - ./mysql:/docker-entrypoint-initdb.d
#   networks:
#     - backend

networks:
  backend:
    driver: bridge
